# Generated by Django 6.1 on 2026-08-26 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_city_remove_profile_street_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rider_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnic', models.CharField(blank=True, help_text='CNIC number (e.g. 35202-1234567-1)', max_length=20)),
                ('vehicle', models.CharField(blank=True, help_text='Vehicle type + plate, e.g. Honda 125 LHR-123', max_length=100)),
                ('zone', models.CharField(blank=True, help_text='Delivery zone, e.g. Gulberg', max_length=80)),
                ('verified', models.BooleanField(default=False, help_text='Fleet verification complete (Tier 2)')),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes about this rider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Rider Profiles',
            },
        ),
        migrations.CreateModel(
            name='RejectedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('cnic', models.CharField(blank=True, max_length=20)),
                ('vehicle', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rejected Application',
                'verbose_name_plural': 'Rejected Applications',
                'ordering': ['-rejected_at'],
            },
        ),
    ]
