# Generated by Django 5.1.4 on 2026-08-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_riderprofile_rejectedapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='duty_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy')], default='offline', help_text="Rider's current duty status (online/offline/busy)", max_length=10),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='lat',
            field=models.FloatField(blank=True, help_text='Ambient GPS latitude (shared while idle/online)', null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='lng',
            field=models.FloatField(blank=True, help_text='Ambient GPS longitude (shared while idle/online)', null=True),
        ),
    ]
