# Generated by Django 6.1 on 2026-08-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='accent',
            field=models.CharField(choices=[('flame', 'Flame'), ('ember', 'Ember'), ('gold', 'Gold'), ('char', 'Char'), ('leaf', 'Leaf')], default='flame', max_length=20),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='chef',
            field=models.CharField(blank=True, default='Chef Kennedy', max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='heat_label',
            field=models.CharField(blank=True, default='Medium', max_length=30),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dish',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ribbon',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('demand', 'In Demand'), ('signature', 'Signature')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='serves',
            field=models.CharField(blank=True, default='2 people', max_length=50),
        ),
        migrations.AddField(
            model_name='dish',
            name='spice_level',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='dish',
            name='story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dish',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dish',
            name='time_label',
            field=models.CharField(blank=True, default='20m', max_length=30),
        ),
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
