# Generated by Django 6.1 on 2026-08-23 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('dish_name', models.CharField(max_length=200)),
                ('dish_image', models.URLField(blank=True)),
                ('size', models.CharField(choices=[('Regular', 'Regular'), ('Large', 'Large'), ('Family', 'Family')], max_length=20)),
                ('qty', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('cod', 'Cash on Delivery')], max_length=20)),
                ('address', models.JSONField()),
                ('rider', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('kitchen', 'In Kitchen'), ('packed', 'Packed'), ('onway', 'On the Way'), ('delivered', 'Delivered')], default='confirmed', max_length=20)),
                ('rider_lat', models.FloatField(blank=True, null=True)),
                ('rider_lng', models.FloatField(blank=True, null=True)),
                ('eta_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
